### ISSUE TITLE
ZLT X28 firmware

### ISSUE THREAD

**Issue by amaleky** [mattfaraday/vn007#4]
I have a ZLT X28 5G Router, I can's access to adb, Got this error:
`{success: false, cmd: 237, message: 'LIMITED_ACCESS'}`
My device is locked and i'm not able to connect any cell, my firmware is based on du isp and it is restricted.
Hardware version: TZ7.823.432
Configuration Version: X28_AE0001-1.09
Software Version: 1.3.0

**Comment by Asad0090090** [comment]
did you get any sloution for this
